### ISSUE TITLE
Error occurred while running npm run serve

### ISSUE THREAD

**Issue by RossComputerGuy** [os-js/osjs-common#1]
```
TypeError: t.provider[e] is not a function
    at t._promise (/opt/os.js/node_modules/@osjs/common/dist/main.js:44:7447)
    at t.signalDependenciesReady (/opt/os.js/node_modules/@osjs/common/dist/main.js:7:5601)
    at /opt/os.js/node_modules/@osjs/common/dist/main.js:7:4162
```

**Comment by andersevenrud** [comment]
Thanks!

This was actually caused by an issue with the dbus service provider. Closing.
